### ISSUE TITLE
Add support for bounds checks during deserialization

### ISSUE THREAD

**Issue by onContentStop** [Koxiaet/bounded-integer#1]
Consider a bounded integer struct that has derived Deserialize:
```rust
use bounded_integer::bounded_integer;
use serde_derive::{Deserialize, Serialize};
bounded_integer! {
    #[derive(Deserialize, Serialize)]
    struct MyBoundedInt { 0..100 }
}
```

Since the struct is a simple tuple struct internally, serde_derive is able to generate an implementation that violates the struct's invariant by bypassing new(). The solution would involve generating a custom Deserialize implementation (?) that calls T::new() instead of whatever the default implementation does.

**Comment by Koxiaet** [comment]
Using 0.2.2, you should be able to add `feature = ["serde"]` and then it will implement `Serialize` and `Deserialize`.
